CREATE TABLE user (
    id BIGINT NOT NULL AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(256) NOT NULL,
    roles VARCHAR(20) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by VARCHAR(50) NOT NULL,
    modified_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    modified_by VARCHAR(50) NOT NULL,
    is_deleted BIT(1) DEFAULT b'0' NOT NULL,
    CONSTRAINT PK_user PRIMARY KEY (id)
)ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;
